services:
  bot:
    image: node:18-alpine
    restart: "always"
    user: node
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    entrypoint: "npm run start"

volumes:
  node_modules:
